name: "Project Integration Tests"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  export-state-example-project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [main]  # Adjust branches/tags as needed

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "19"

      - name: SetUp ois-core
        run: |
          git clone https://github.com/attiasas/ois-core.git --branch ${{ matrix.branch }}
          cd ois-core
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./gradlew.bat publishToMavenLocal
          else
            chmod +x gradlew
            ./gradlew publishToMavenLocal
          fi
          cd ..  # Return to the main project working directory
        shell: bash

      - name: Publish Plugin to MavenLocal
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            ./gradlew.bat publishToMavenLocal
          else
            chmod +x gradlew
            ./gradlew publishToMavenLocal
          fi
        shell: bash

      - name: Run Export Task
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./gradlew.bat -p src\\test\\resources\\projects\\state-example export --info
          else
            ./gradlew -p src/test/resources/projects/state-example export --info
          fi
        shell: bash

      - name: Check Files in Distribution Directories with Minimum Count
        run: |
          # Base path for directories to check
          base_dir="src/test/resources/projects/state-example/build/ois/distribution"
          
          # Define directory names with required minimum count (format: "dir_name:exact_count")
          dir_requirements=("Html:1" "Desktop:0")
          
          # Iterate through each directory name and check conditions
          for entry in "${dir_requirements[@]}"; do
            # Split entry into name and exact_count using parameter expansion
            dir_name="${entry%%:*}"
            exact_count="${entry##*:}"
            dir_path="$base_dir/$dir_name"
          
            # Check if the directory exists
            if [ -d "$dir_path" ]; then
              # Count files and directories within the current directory
              actual_count=$(find "$dir_path" -type f -or -type d | wc -l) - 1
          
              # Check if the actual count meets or exceeds the minimum required count
              if [ "$actual_count" -eq "$exact_count" ]; then
                echo "Directory $dir_path has the exact required count ($actual_count items):"
                # List directory contents based on the OS
                if [[ ${{ matrix.os }} == "windows-latest" ]]; then
                  dir "$dir_path"
                else
                  ls -la "$dir_path"
                fi
              else
                echo "Directory $dir_path does not meet the exact required count. Expected $exact_count, but found $actual_count." && exit 1
              fi
            else
              echo "Directory does not exist: $dir_path" && exit 1
            fi
          done
        shell: bash