name: "Project Integration Tests"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-state-example-project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [simulation_engine]  # Adjust branches/tags as needed

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "19"

      - name: SetUp ois-core
        run: |
          git clone https://github.com/attiasas/ois-core.git --branch ${{ matrix.branch }}
          cd ois-core
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            ./gradlew.bat publishToMavenLocal
          else
            chmod +x gradlew
            ./gradlew publishToMavenLocal
          fi
          cd ..  # Return to the main project working directory
        shell: bash

      - name: Publish Plugin to MavenLocal
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            ./gradlew.bat publishToMavenLocal
          else
            chmod +x gradlew
            ./gradlew publishToMavenLocal
          fi
        shell: bash

#      - name: Run HTML Task on Project
#        run: |
#          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
#            Start-Process -NoNewWindow -FilePath ./gradlew.bat -ArgumentList "-p src\\test\\resources\\projects\\state-example runHtml" | Out-File -FilePath output.log -Append
#            while (!(Select-String -Path output.log -Pattern "http://localhost:8080/")) { Start-Sleep -Seconds 5 }
#          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
#            ./gradlew -p src/test/resources/projects/state-example runHtml | tee output.log &
#            while ! grep -q "http://localhost:8080/" output.log; do sleep 5; done
#          else
#            ./gradlew -p src/test/resources/projects/state-example runHtml | tee output.log &
#            while ! grep -q "http://localhost:8080/" output.log; do sleep 5; done
#          fi
#        shell: bash

      - name: Complete Task
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            echo "Any key to finish the task" | cat > NUL
          else
            echo "Any key to finish the theask" | cat > /dev/null
          fi

  export-state-example-project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        branch: [simulation_engine]  # Adjust branches/tags as needed

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "19"

      - name: SetUp ois-core
        run: |
          git clone https://github.com/attiasas/ois-core.git --branch ${{ matrix.branch }}
          cd ois-core
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./gradlew.bat publishToMavenLocal
          else
            chmod +x gradlew
            ./gradlew publishToMavenLocal
          fi
          cd ..  # Return to the main project working directory
        shell: bash

      - name: Publish Plugin to MavenLocal
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then
            ./gradlew.bat publishToMavenLocal
          else
            chmod +x gradlew
            ./gradlew publishToMavenLocal
          fi
        shell: bash

      - name: Run Export Task
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ./gradlew.bat -p src\\test\\resources\\projects\\state-example export
          else
            ./gradlew -p src/test/resources/projects/state-example export
          fi
        shell: bash

      - name: Check Files in Distribution Directory
        run: |
          dir="src/test/resources/projects/state-example/build/distribution/html"

          # Check if there are any files in the directory
          if find "$dir" -type f -print -quit | grep -q .; then
            echo "Files exist in the directory."
          else
            echo "No files found in the directory."
          fi
          
          # Check the OS and print directory contents accordingly
          if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
            # Windows environment
            echo "Listing files in $dir (Windows):"
            dir "$dir"
          else
            # Linux or macOS
            echo "Listing files in $dir (Unix-like):"
            ls -la "$dir"
          fi

#           if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
#            if (Test-Path -Path "src\\test\\resources\\projects\\state-example\\build\\distribution\\html" -and (Get-ChildItem -Path "src\\test\\resources\\projects\\state-example\\build\\distribution\\html" | Measure-Object).Count -gt 0) {
#              Write-Output "Files were successfully created in build\\distribution\\html."
#            } else {
#              Write-Output "No files found in build\\distribution\\html" ; exit 1
#            }
#          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
#            if [ -d "src/test/resources/projects/state-example/build/distribution/html" ] && [ "$(ls -A src/test/resources/projects/state-example/build/distribution/html)" ]; then
#              echo "Files were successfully created in build/distribution/html."
#            else
#              echo "No files found in build/distribution/html" && exit 1
#            fi
#          else
#            if [ -d "src/test/resources/projects/state-example/build/distribution/html" ] && [ "$(ls -A src/test/resources/projects/state-example/build/distribution/html)" ]; then
#              echo "Files were successfully created in build/distribution/html."
#            else
#              echo "No files found in build/distribution/html" && exit 1
#            fi
#          fi
        shell: bash
